// Code generated by command: go run asm.go -out ../stringstop_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func stringStopIndexAVX2(data []byte) int
// Requires: AVX, AVX2, BMI
TEXT ·stringStopIndexAVX2(SB), NOSPLIT, $0-32
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	VPBROADCASTB c1f<>+0(SB), Y0
	VPBROADCASTB c22<>+0(SB), Y1
	VPBROADCASTB c5c<>+0(SB), Y2
	XORQ         DX, DX

loop32:
	LEAQ      32(DX), BX
	CMPQ      BX, CX
	JG        tail
	VMOVDQU   (AX)(DX*1), Y3
	VPMINUB   Y3, Y0, Y4
	VPCMPEQB  Y4, Y3, Y4
	VPCMPEQB  Y3, Y1, Y5
	VPCMPEQB  Y3, Y2, Y3
	VPOR      Y4, Y5, Y4
	VPOR      Y4, Y3, Y4
	VPMOVMSKB Y4, BX
	TESTL     BX, BX
	JNZ       found
	ADDQ      $0x20, DX
	JMP       loop32

found:
	TZCNTL BX, AX
	ADDQ   AX, DX
	MOVQ   DX, ret+24(FP)
	VZEROUPPER
	RET

tail:
tailloop:
	CMPQ    DX, CX
	JGE     notfound
	MOVBLZX (AX)(DX*1), BX
	CMPL    BX, $0x20
	JL      foundtail
	CMPL    BX, $0x22
	JE      foundtail
	CMPL    BX, $0x5c
	JE      foundtail
	INCQ    DX
	JMP     tailloop

foundtail:
	MOVQ DX, ret+24(FP)
	VZEROUPPER
	RET

notfound:
	MOVQ CX, ret+24(FP)
	VZEROUPPER
	RET

DATA c1f<>+0(SB)/1, $0x1f
GLOBL c1f<>(SB), RODATA|NOPTR, $1

DATA c22<>+0(SB)/1, $0x22
GLOBL c22<>(SB), RODATA|NOPTR, $1

DATA c5c<>+0(SB)/1, $0x5c
GLOBL c5c<>(SB), RODATA|NOPTR, $1
