// Code generated by command: go run asm.go -out ../stringstop_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func stringStopIndexAVX2(data []byte) (int, bool)
// Requires: AVX, AVX2, BMI
TEXT ·stringStopIndexAVX2(SB), NOSPLIT, $0-33
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	XORL         DX, DX
	VPBROADCASTB c1f<>+0(SB), Y0
	VPBROADCASTB c22<>+0(SB), Y1
	VPBROADCASTB c5c<>+0(SB), Y2
	XORQ         BX, BX

loop32:
	LEAQ      32(BX), SI
	CMPQ      SI, CX
	JG        tail
	VMOVDQU   (AX)(BX*1), Y3
	VPMINUB   Y3, Y0, Y4
	VPCMPEQB  Y4, Y3, Y4
	VPCMPEQB  Y3, Y1, Y5
	VPCMPEQB  Y3, Y2, Y6
	VPOR      Y4, Y5, Y4
	VPOR      Y4, Y6, Y4
	VPMOVMSKB Y3, SI
	VPMOVMSKB Y4, DI
	TESTL     DI, DI
	JNZ       found
	ORL       SI, DX
	ADDQ      $0x20, BX
	JMP       loop32

found:
	TZCNTL DI, AX
	MOVL   DI, CX
	DECL   CX
	NOTL   DI
	ANDL   DI, CX
	ANDL   CX, SI
	ORL    SI, DX
	ADDQ   AX, BX
	MOVQ   BX, ret+24(FP)
	TESTL  DX, DX
	SETNE  AL
	MOVB   AL, ret1+32(FP)
	VZEROUPPER
	RET

tail:
tailloop:
	CMPQ    BX, CX
	JGE     notfound
	MOVBLZX (AX)(BX*1), SI
	CMPL    SI, $0x20
	JL      foundtail
	CMPL    SI, $0x22
	JE      foundtail
	CMPL    SI, $0x5c
	JE      foundtail
	ANDL    $0x80, SI
	ORL     SI, DX
	INCQ    BX
	JMP     tailloop

foundtail:
	MOVQ  BX, ret+24(FP)
	TESTL DX, DX
	SETNE AL
	MOVB  AL, ret1+32(FP)
	VZEROUPPER
	RET

notfound:
	MOVQ  CX, ret+24(FP)
	TESTL DX, DX
	SETNE AL
	MOVB  AL, ret1+32(FP)
	VZEROUPPER
	RET

DATA c1f<>+0(SB)/1, $0x1f
GLOBL c1f<>(SB), RODATA|NOPTR, $1

DATA c22<>+0(SB)/1, $0x22
GLOBL c22<>(SB), RODATA|NOPTR, $1

DATA c5c<>+0(SB)/1, $0x5c
GLOBL c5c<>(SB), RODATA|NOPTR, $1
