//nolint:dupl // writegen lifts commonWriter verbatim onto each concrete writer; the triplication is by design.
package writer

import (
	"encoding"
	"errors"
	"fmt"
	"io"
	"math/big"
	"unicode/utf8"
	"unsafe"

	"github.com/go-openapi/core/json/lexers/token"
	"github.com/go-openapi/core/json/stores/values"
	"github.com/go-openapi/core/json/types"
	"github.com/go-openapi/core/json/writers"
	"github.com/go-openapi/swag/conv"
)

var (
	_ writers.StoreWriter    = &Unbuffered{}
	_ writers.JSONWriter     = &Unbuffered{}
	_ writers.TokenWriter    = &Unbuffered{}
	_ writers.VerbatimWriter = &Unbuffered{}
)

//go:generate go run ./internal/writegen -target Unbuffered

// Unbuffered JSON writer.
// [Unbuffered] implements
// [writers.StoreWriter], [writers.JSONWriter], [writers.TokenWriter] and [writers.VerbatimWriter].
//
// It knows how to render JSON tokens and JSON values to an underlying [io.Writer].
//
// All writes are passed straight-through, and no flushing is required.
//
// Strings are escaped with default JSON escaping rule for tabs, new lines, line feeds, backslashes and double quotes.
//
// There is no attempt to do anything special regarding empty or null values:
//
//   - an undefined value (or nil data) is not rendered
//   - a null value is necessarily defined explicitly and is rendered with the "null" token
//
// # Concurrency
//
// [Unbuffered] is not intended for concurrent use.
type Unbuffered struct {
	unbuffered
	commonWriter[*unbuffered]
}

type unbuffered struct {
	baseWriter

	bw      io.ByteWriter // w.w asserted to io.ByteWriter once (nil if unsupported); avoids a per-call type assertion
	scratch [1]byte       // reused for single-byte writes to avoid a per-call allocation
}

// NewUnbuffered JSON writer that copies JSON to [io.Writer] w, without buffering.
//
// [Unbuffered] has no configurable options and holds no pooled resources, so there is nothing to
// relinquish: no options finalizer is registered.
func NewUnbuffered(w io.Writer, _ ...UnbufferedOption) *Unbuffered {
	writer := &Unbuffered{
		unbuffered: unbuffered{
			baseWriter: baseWriter{
				w: w,
			},
		},
	}
	writer.jw = &writer.unbuffered
	writer.bw, _ = w.(io.ByteWriter)

	return writer
}

func (w *Unbuffered) Reset() {
	w.baseWriter.Reset()
}

// redeem has no inner resources to relinquish for the Unbuffered writer.
func (w *unbuffered) redeem() {}

func (w *unbuffered) writeSingleByte(c byte) {
	if w.err != nil {
		return
	}

	if w.bw != nil {
		w.err = w.bw.WriteByte(c)
		if w.err == nil {
			w.inc(1)
		}

		return
	}

	// w.scratch is part of the (heap-allocated) writer, so slicing it does not allocate,
	// unlike a fresh []byte{c} literal which escapes through the io.Writer interface.
	w.scratch[0] = c
	n, err := w.w.Write(w.scratch[:])
	w.err = err
	w.inc(n)
}

func (w *unbuffered) writeBinary(data []byte) {
	n, err := w.w.Write(data)
	w.inc(n)
	w.err = err
}

// writeEscaped escapes data and writes it straight through to the underlying writer.
//
// Like [buffered.writeEscaped], it returns any trailing bytes that form an incomplete UTF-8
// rune (e.g. a multi-byte rune split across a read boundary in [commonWriter.StringCopy]),
// rather than treating them as an error. The caller decides whether the remainder is a
// genuine truncation or should be stitched with the next read.
func (w *unbuffered) writeEscaped(data []byte) []byte {
	if w.err != nil {
		return nil
	}

	escapedHolder, redeemEscaped := poolOfEscapedBuffers.BorrowWithSizeAndRedeem(len(data))
	escapedBuffer := escapedHolder.Slice()
	escapedBuffer, remainder := escapedBytes(data, escapedBuffer)
	w.writeBinary(escapedBuffer)
	redeemEscaped()

	// remainder points into data (the caller's buffer), so it stays valid after redeem.
	return remainder
}

// Comma is generated by writegen from commonWriter.Comma; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Comma() {
	w.jw.writeSingleByte(comma)
}

// Colon is generated by writegen from commonWriter.Colon; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Colon() {
	w.jw.writeSingleByte(colon)
}

// EndArray is generated by writegen from commonWriter.EndArray; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) EndArray() {
	w.jw.writeSingleByte(closingSquareBracket)
}

// EndObject is generated by writegen from commonWriter.EndObject; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) EndObject() {
	w.jw.writeSingleByte(closingBracket)
}

// StartArray is generated by writegen from commonWriter.StartArray; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) StartArray() {
	w.jw.writeSingleByte(openingSquareBracket)
}

// StartObject is generated by writegen from commonWriter.StartObject; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) StartObject() {
	w.jw.writeSingleByte(openingBracket)
}

// Bool is generated by writegen from commonWriter.Bool; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Bool(v bool) {
	if !w.jw.Ok() {
		return
	}

	if v {
		w.jw.writeBinary(trueBytes)

		return
	}

	w.jw.writeBinary(falseBytes)
}

// Raw is generated by writegen from commonWriter.Raw; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Raw(data []byte) {
	if !w.jw.Ok() || len(data) == 0 {
		return
	}

	w.jw.writeBinary(data)
}

// String is generated by writegen from commonWriter.String; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) String(s string) {
	if !w.jw.Ok() {
		return
	}

	w.writeTextString(s)
}

// StringBytes is generated by writegen from commonWriter.StringBytes; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) StringBytes(data []byte) {
	if !w.jw.Ok() || data == nil {
		return
	}

	w.writeText(data)
}

// StringRunes is generated by writegen from commonWriter.StringRunes; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) StringRunes(data []rune) {
	if !w.jw.Ok() || data == nil {
		return
	}
	// worst case is utf8.UTFMax (4) bytes per rune. utf8.MaxRune is a code point, not a
	// byte width: using it here over-allocates by ~280,000x.
	holder, redeem := poolOfEscapedBuffers.BorrowWithSizeAndRedeem(len(data) * utf8.UTFMax)
	defer redeem()

	buf := holder.Slice()
	for _, r := range data {
		buf = utf8.AppendRune(buf, r)
	}

	w.writeText(buf)
}

// NumberBytes is generated by writegen from commonWriter.NumberBytes; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) NumberBytes(data []byte) {
	if !w.jw.Ok() || len(data) == 0 {
		return
	}

	w.jw.writeBinary(data)
}

// NumberCopy is generated by writegen from commonWriter.NumberCopy; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) NumberCopy(r io.Reader) {
	w.RawCopy(r)
}

// RawCopy is generated by writegen from commonWriter.RawCopy; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) RawCopy(r io.Reader) {
	if !w.jw.Ok() {
		return
	}

	bufHolder, redeemReadBuffer := poolOfReadBuffers.BorrowWithRedeem()
	buf := bufHolder.Slice()

	for {
		n, err := r.Read(buf)
		if err != nil && !errors.Is(err, io.EOF) {
			w.jw.SetErr(err)

			break
		}

		if n > 0 {
			w.jw.writeBinary(buf[:n])
			if !w.jw.Ok() {
				break
			}
		}

		if n == 0 || (err != nil && errors.Is(err, io.EOF)) {
			break
		}
	}

	redeemReadBuffer()
}

// StringCopy is generated by writegen from commonWriter.StringCopy; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) StringCopy(r io.Reader) {
	w.jw.writeSingleByte(quote)
	if !w.jw.Ok() {
		return
	}

	var remainder []byte
	bufHolder, redeemReadBuffer := poolOfReadBuffers.BorrowWithRedeem()
	defer func() {
		redeemReadBuffer()
	}()

	buf := bufHolder.Slice()

	for {
		n, err := r.Read(buf)
		if err != nil && !errors.Is(err, io.EOF) {
			w.jw.SetErr(err)

			return
		}

		if n > 0 {
			remainder = w.jw.writeEscaped(buf[:n])
			if !w.jw.Ok() {
				return
			}

			notWritten := len(remainder)
			if notWritten > 0 {
				// if the previous read reported an incomplete rune, consume the expected remaining bytes and realign to runes
				if notWritten > utf8.UTFMax {
					w.jw.SetErr(
						fmt.Errorf(
							"unexpected incomplete rune (remainder larger than possible rune): %c : %w",
							remainder,
							ErrDefaultWriter,
						),
					)

					return
				}

				runeSize := completeRuneSize(remainder[0]) // TODO: check if 0 (invalid)
				if runeSize == 0 {
					w.jw.SetErr(
						fmt.Errorf(
							"unexpected incomplete rune (invalid first byte): %c: %w",
							remainder,
							ErrDefaultWriter,
						),
					)

					return
				}

				var single [utf8.UTFMax]byte
				copy(single[:], remainder)

				// Read exactly the missing bytes of the split rune. io.ReadFull tolerates
				// short reads (e.g. a reader that yields one byte at a time) and only fails
				// when the input ends before the rune is complete.
				// Note: this must not clobber the outer loop's n/err, which drive termination.
				if _, rerr := io.ReadFull(r, single[notWritten:runeSize]); rerr != nil {
					if errors.Is(rerr, io.EOF) || errors.Is(rerr, io.ErrUnexpectedEOF) {
						w.jw.SetErr(
							fmt.Errorf(
								"unexpected incomplete rune at end of input: %c: %w",
								remainder,
								ErrDefaultWriter,
							),
						)

						return
					}

					w.jw.SetErr(rerr)

					return
				}

				remainder = w.jw.writeEscaped(single[:runeSize])
				if !w.jw.Ok() {
					return
				}
				if len(remainder) > 0 {
					w.jw.SetErr(
						fmt.Errorf(
							"unexpected incomplete rune at end of input: %c: %w",
							remainder,
							ErrDefaultWriter,
						),
					)

					return
				}
			}
		}

		if n == 0 || (err != nil && errors.Is(err, io.EOF)) {
			break
		}
	}

	w.jw.writeSingleByte(quote)
}

// JSONString is generated by writegen from commonWriter.JSONString; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) JSONString(value types.String) {
	if !w.jw.Ok() || !value.IsDefined() {
		return
	}

	w.writeText(value.Value)
}

// JSONNumber is generated by writegen from commonWriter.JSONNumber; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) JSONNumber(value types.Number) {
	if !w.jw.Ok() || !value.IsDefined() || len(value.Value) == 0 {
		return
	}

	w.jw.writeBinary(value.Value)
}

// JSONBoolean is generated by writegen from commonWriter.JSONBoolean; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) JSONBoolean(value types.Boolean) {
	if !w.jw.Ok() || !value.IsDefined() {
		return
	}

	w.Bool(value.Value)
}

// JSONNull is generated by writegen from commonWriter.JSONNull; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) JSONNull(value types.NullType) {
	if !w.jw.Ok() || !value.IsDefined() {
		return
	}

	w.jw.writeBinary(nullToken)
}

// Value is generated by writegen from commonWriter.Value; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Value(v values.Value) {
	switch v.Kind() {
	case token.String:
		w.StringBytes(v.StringValue().Value)
	case token.Number:
		w.NumberBytes(v.NumberValue().Value)
	case token.Boolean:
		w.Bool(v.Bool())
	case token.Null:
		w.Null()
	default:
		// skip
	}
}

// Null is generated by writegen from commonWriter.Null; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Null() {
	if !w.jw.Ok() {
		return
	}

	w.jw.writeBinary(nullToken)
}

// Key is generated by writegen from commonWriter.Key; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Key(key values.InternedKey) {
	w.String(key.String())
	w.Colon()
}

// Number is generated by writegen from commonWriter.Number; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Number(v any) {
	if !w.jw.Ok() {
		return
	}

	holder, redeem := poolOfNumberBuffers.BorrowWithRedeem()
	defer redeem()
	dst := holder.Slice()

	switch n := v.(type) {
	case uint8:
		w.jw.writeBinary(conv.AppendUinteger(dst, n))
	case uint16:
		w.jw.writeBinary(conv.AppendUinteger(dst, n))
	case uint32:
		w.jw.writeBinary(conv.AppendUinteger(dst, n))
	case uint64:
		w.jw.writeBinary(conv.AppendUinteger(dst, n))
	case uint:
		w.jw.writeBinary(conv.AppendUinteger(dst, n))
	case int8:
		w.jw.writeBinary(conv.AppendInteger(dst, n))
	case int16:
		w.jw.writeBinary(conv.AppendInteger(dst, n))
	case int32:
		w.jw.writeBinary(conv.AppendInteger(dst, n))
	case int64:
		w.jw.writeBinary(conv.AppendInteger(dst, n))
	case int:
		w.jw.writeBinary(conv.AppendInteger(dst, n))
	case float32:
		w.jw.writeBinary(conv.AppendFloat(dst, n))
	case float64:
		w.jw.writeBinary(conv.AppendFloat(dst, n))
	case []byte:
		w.jw.writeBinary(n)
	case *big.Int:
		if n == nil {
			return
		}
		w.append(n)
		return
	case big.Int:
		w.append(&n)
		return
	case *big.Rat:
		if n == nil {
			return
		}
		f, _ := n.Float64()
		w.jw.writeBinary(conv.AppendFloat(dst, f))
	case big.Rat:
		f, _ := n.Float64()
		w.jw.writeBinary(conv.AppendFloat(dst, f))
	case *big.Float:
		if n == nil {
			return
		}
		w.appendFloat(n)
		return
	case big.Float:
		w.appendFloat(&n)
		return
	default:
		panic(fmt.Errorf(
			"expected argument to Number() to be of a numerical type, but got: %T: %w",
			v, ErrDefaultWriter,
		))
	}
}

// Token is generated by writegen from commonWriter.Token; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) Token(tok token.T) {
	if !w.jw.Ok() {
		return
	}

	switch tok.Kind() {
	case token.Delimiter:
		switch tok.Delimiter() {
		case token.OpeningBracket:
			w.StartObject()
		case token.ClosingBracket:
			w.EndObject()
		case token.OpeningSquareBracket:
			w.StartArray()
		case token.ClosingSquareBracket:
			w.EndArray()
		case token.Comma:
			w.Comma()
		case token.Colon:
			w.Colon()
		default:
			// ignore
		}
	case token.String, token.Key:
		w.writeText(tok.Value())
	case token.Number:
		w.NumberBytes(tok.Value())
	case token.Boolean:
		w.Bool(tok.Bool())
	case token.Null:
		w.Null()
	case token.EOF:
		fallthrough
	default:
		// ignore
	}
}

// VerbatimToken is generated by writegen from commonWriter.VerbatimToken; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) VerbatimToken(leadingSpace []byte, tok token.T) {
	if !w.jw.Ok() {
		return
	}

	w.jw.writeBinary(leadingSpace)

	if k := tok.Kind(); k == token.String || k == token.Key {
		w.jw.writeSingleByte(quote)
		w.jw.writeBinary(tok.Value())
		w.jw.writeSingleByte(quote)

		return
	}

	w.Token(tok)
}

// VerbatimValue is generated by writegen from commonWriter.VerbatimValue; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) VerbatimValue(value values.VerbatimValue) {
	if !w.jw.Ok() {
		return
	}

	w.jw.writeBinary(value.Blanks())
	w.Value(value.Value)
}

// append is generated by writegen from commonWriter.append; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) append(n encoding.TextAppender) {
	buf, redeem := poolOfNumberBuffers.BorrowWithRedeem()
	defer redeem()
	b := buf.Slice()

	b, err := n.AppendText(b)
	if err != nil {
		w.jw.SetErr(err)

		return
	}

	w.jw.writeBinary(b)
}

// appendFloat is generated by writegen from commonWriter.appendFloat; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) appendFloat(n *big.Float) {
	buf, redeem := poolOfNumberBuffers.BorrowWithRedeem()
	defer redeem()
	b := buf.Slice()

	// MinPrec() keeps the conversion allocation-free for the common float64-backed case.
	// It prints the full binary expansion (e.g. 12.23 -> 12.2300…426) rather than the
	// shortest round-trip form, but the value is exact; prec -1 would roughly double allocs.
	b = n.Append(b, 'g', int(n.MinPrec()))
	w.jw.writeBinary(b)
}

// writeTextString is generated by writegen from commonWriter.writeTextString; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) writeTextString(input string) {
	b := unsafe.Slice(unsafe.StringData(input), len(input))
	w.writeText(b)
}

// writeText is generated by writegen from commonWriter.writeText; DO NOT EDIT (edit commonWriter, re-run go generate).
func (w *Unbuffered) writeText(data []byte) {
	w.jw.writeSingleByte(quote)
	remainder := w.jw.writeEscaped(data)
	if len(remainder) > 0 {
		w.jw.SetErr(
			fmt.Errorf(
				"unexpected incomplete rune (invalid first byte): %c: %w",
				remainder,
				ErrDefaultWriter,
			),
		)

		return
	}
	w.jw.writeSingleByte(quote)
}
