// Command writegen lifts the generic commonWriter[T] methods onto a concrete writer type
// (Buffered, Unbuffered) as verbatim copies with the receiver swapped.
//
// Why: calls through the type parameter T (e.g. w.jw.writeSingleByte) compile to a dictionary
// call that the compiler will not inline. The same body on a concrete receiver — where the
// embedded commonWriter[*concrete].jw field is statically typed — inlines. commonWriter[T]
// stays the single source of truth; the lifted methods are byte-for-byte its bodies, so they
// cannot drift. The generic instantiation methods become dead code and are eliminated.
//
// The generated methods are injected in place into the target's own file, each tagged with a
// marker comment; re-running strips the marked methods and re-injects, so it is idempotent.
//
// Usage (via go:generate, run from the package directory):
//
//	//go:generate go run ./internal/writegen -target Buffered
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	goFilePerm  = 0o644
	genericType = "commonWriter"
	markerTag   = "generated by writegen from commonWriter."
	// markerDetect is the stable token that identifies a previously-injected method, used to
	// strip them on regeneration. Keep it stable even if markerTag wording changes.
	markerDetect = "writegen"
	localPrefix  = "github.com/fredbi/core"
)

var (
	errTargetNotFound = errors.New("target type not found in package")
	errNoMethods      = errors.New("no commonWriter[T] methods found to lift")
	errNoImportDecl   = errors.New("no import declaration found")
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("writegen: ")

	target := flag.String("target", "", "concrete writer type to lift onto (e.g. Buffered)")
	flag.Parse()
	if *target == "" {
		log.Fatal("missing -target")
	}

	if err := run(*target); err != nil {
		log.Fatal(err)
	}
}

type sourceFile struct {
	path string
	src  []byte
	ast  *ast.File
}

func run(target string) error {
	fset := token.NewFileSet()

	goFiles, err := filepath.Glob("*.go")
	if err != nil {
		return err
	}

	files := make([]sourceFile, 0, len(goFiles))
	for _, path := range goFiles {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
		if err != nil {
			return err
		}
		files = append(files, sourceFile{path: path, src: src, ast: f})
	}

	// collect the generic methods (source of truth) and the catalog of importable packages
	catalog := map[string]importSpec{} // package name -> import spec
	var lifted []string                // generated method texts, receiver-swapped
	var names []string                 // method names (for the markers)
	var targetFile *sourceFile

	for i := range files {
		f := &files[i]
		addImports(catalog, f.ast)

		for _, decl := range f.ast.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if recvTypeName(d) != genericType {
					continue
				}
				name := d.Name.Name
				body := nodeText(f.src, fset, d)
				body = strings.ReplaceAll(body, "*"+genericType+"[T]", "*"+target)
				lifted = append(lifted, body)
				names = append(names, name)
			case *ast.GenDecl:
				if d.Tok == token.TYPE && declaresType(d, target) {
					targetFile = f
				}
			}
		}
	}

	if targetFile == nil {
		return fmt.Errorf("%w: %s", errTargetNotFound, target)
	}
	if len(lifted) == 0 {
		return errNoMethods
	}

	// 1. strip previously injected methods from the target source
	stripped := stripMarked(targetFile.src, fset, targetFile.ast, target)

	// 2. append the freshly lifted methods
	var out bytes.Buffer
	out.Write(bytes.TrimRight(stripped, "\n"))
	out.WriteString("\n")
	for i, body := range lifted {
		// doc comment starts with the symbol name (godoc convention) and carries the marker
		// tag used to find & replace these on re-generation.
		fmt.Fprintf(&out, "\n// %s is %s%s; DO NOT EDIT (edit commonWriter, re-run go generate).\n",
			names[i], markerTag, names[i])
		out.WriteString(body)
		out.WriteString("\n")
	}

	// 3. fix the import block from the actual usage of the combined file
	combined, err := fixImports(fset, out.Bytes(), catalog)
	if err != nil {
		return err
	}

	formatted, err := format.Source(combined)
	if err != nil {
		return fmt.Errorf("formatting %s: %w", targetFile.path, err)
	}

	if err := os.WriteFile(targetFile.path, formatted, goFilePerm); err != nil {
		return err
	}

	log.Printf("lifted %d methods onto %s in %s", len(lifted), target, targetFile.path)

	return nil
}

// recvTypeName returns the base type name of a method receiver, stripping pointer and type
// arguments: (w *commonWriter[T]) -> "commonWriter". Returns "" for non-methods.
func recvTypeName(d *ast.FuncDecl) string {
	if d.Recv == nil || len(d.Recv.List) == 0 {
		return ""
	}
	expr := d.Recv.List[0].Type
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if idx, ok := expr.(*ast.IndexExpr); ok { // commonWriter[T]
		expr = idx.X
	}
	if id, ok := expr.(*ast.Ident); ok {
		return id.Name
	}

	return ""
}

func declaresType(d *ast.GenDecl, name string) bool {
	for _, spec := range d.Specs {
		if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.Name == name {
			return true
		}
	}

	return false
}

func nodeText(src []byte, fset *token.FileSet, n ast.Node) string {
	return string(src[fset.Position(n.Pos()).Offset:fset.Position(n.End()).Offset])
}

// stripMarked removes every FuncDecl on the target type carrying the marker comment, returning
// the source with those regions (marker comment included) cut out.
func stripMarked(src []byte, fset *token.FileSet, f *ast.File, target string) []byte {
	type span struct{ start, end int }
	var spans []span

	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || recvTypeName(fn) != target {
			continue
		}
		if fn.Doc == nil || !strings.Contains(fn.Doc.Text(), markerDetect) {
			continue
		}
		spans = append(spans, span{
			start: fset.Position(fn.Doc.Pos()).Offset,
			end:   fset.Position(fn.End()).Offset,
		})
	}

	// cut from the bottom up so offsets stay valid
	sort.Slice(spans, func(i, j int) bool { return spans[i].start > spans[j].start })
	out := append([]byte(nil), src...)
	for _, s := range spans {
		out = append(out[:s.start], out[s.end:]...)
	}

	return out
}

type importSpec struct {
	alias string // "" when the import uses the package's own name
	path  string
}

func addImports(catalog map[string]importSpec, f *ast.File) {
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		spec := importSpec{path: path}
		name := packageName(path)
		if imp.Name != nil {
			spec.alias = imp.Name.Name
			name = imp.Name.Name
		}
		catalog[name] = spec
	}
}

func packageName(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[i+1:]
	}

	return path
}

// fixImports rewrites the import block of src to exactly the packages it references, grouped
// std / third-party / local and sorted. names are resolved against catalog.
func fixImports(fset *token.FileSet, src []byte, catalog map[string]importSpec) ([]byte, error) {
	f, err := parser.ParseFile(fset, "combined.go", src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("re-parsing generated source: %w", err)
	}

	used := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		id, ok := sel.X.(*ast.Ident)
		if !ok || id.Obj != nil { // Obj != nil => resolves to a local decl, not a package
			return true
		}
		if _, isPkg := catalog[id.Name]; isPkg {
			used[id.Name] = true
		}

		return true
	})

	specs := make([]importSpec, 0, len(used))
	for name := range used {
		specs = append(specs, catalog[name])
	}

	block := buildImportBlock(specs)

	// locate the existing import GenDecl and replace its span
	var importDecl *ast.GenDecl
	for _, decl := range f.Decls {
		if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok == token.IMPORT {
			importDecl = gd

			break
		}
	}
	if importDecl == nil {
		return nil, errNoImportDecl
	}

	start := fset.Position(importDecl.Pos()).Offset
	end := fset.Position(importDecl.End()).Offset

	var out bytes.Buffer
	out.Write(src[:start])
	out.WriteString(block)
	out.Write(src[end:])

	return out.Bytes(), nil
}

func buildImportBlock(specs []importSpec) string {
	var std, third, local []importSpec
	for _, s := range specs {
		switch {
		case strings.HasPrefix(s.path, localPrefix):
			local = append(local, s)
		case isStdlib(s.path):
			std = append(std, s)
		default:
			third = append(third, s)
		}
	}

	var b strings.Builder
	b.WriteString("import (")
	first := true
	for _, group := range [][]importSpec{std, third, local} {
		if len(group) == 0 {
			continue
		}
		sort.Slice(group, func(i, j int) bool { return group[i].path < group[j].path })
		b.WriteString("\n")
		if !first {
			b.WriteString("\n")
		}
		first = false
		for _, s := range group {
			if s.alias != "" && s.alias != packageName(s.path) {
				fmt.Fprintf(&b, "\t%s %q", s.alias, s.path)
			} else {
				fmt.Fprintf(&b, "\t%q", s.path)
			}
			b.WriteString("\n")
		}
	}
	b.WriteString(")")

	return b.String()
}

func isStdlib(path string) bool {
	first, _, _ := strings.Cut(path, "/")

	return !strings.Contains(first, ".")
}
