name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test-monorepo.yml@d2d2b54984441dbea93c5672174cd949c60b4fc5 # v0.5.3
    with:
      extra-flags: '-tags poolsdebug'
    secrets: inherit
