name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@d2d2b54984441dbea93c5672174cd949c60b4fc5 # v0.5.3
    with:
      tag: ${{ github.ref_name }}
      is-monorepo: true
    secrets: inherit
