// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

// Code generated by command: go run asm.go -out ../validate_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func validateUTF8BlocksAVX2(data []byte) bool
// Requires: AVX, AVX2
TEXT ·validateUTF8BlocksAVX2(SB), NOSPLIT, $0-25
	MOVQ           data_base+0(FP), AX
	MOVQ           data_len+8(FP), CX
	VBROADCASTI128 utf8t1h<>+0(SB), Y0
	VBROADCASTI128 utf8t1l<>+0(SB), Y1
	VBROADCASTI128 utf8t2h<>+0(SB), Y2
	VPBROADCASTB   utf8n<>+0(SB), Y3
	VPBROADCASTB   utf8h<>+0(SB), Y4
	VPBROADCASTB   utf8c3<>+0(SB), Y5
	VPBROADCASTB   utf8c4<>+0(SB), Y6
	VPXOR          Y7, Y7, Y7
	VPXOR          Y8, Y8, Y8
	XORQ           DX, DX

utf8loop:
	VMOVDQU    (AX)(DX*1), Y9
	VPERM2I128 $0x21, Y9, Y7, Y7
	VPALIGNR   $0x0f, Y7, Y9, Y10
	VPALIGNR   $0x0e, Y7, Y9, Y11
	VPALIGNR   $0x0d, Y7, Y9, Y7
	VPSRLW     $0x04, Y10, Y12
	VPAND      Y3, Y12, Y12
	VPSHUFB    Y12, Y0, Y13
	VPAND      Y3, Y10, Y12
	VPSHUFB    Y12, Y1, Y10
	VPSRLW     $0x04, Y9, Y12
	VPAND      Y3, Y12, Y12
	VPSHUFB    Y12, Y2, Y12
	VPAND      Y13, Y10, Y10
	VPAND      Y12, Y10, Y10
	VPSUBUSB   Y5, Y11, Y11
	VPSUBUSB   Y6, Y7, Y7
	VPOR       Y7, Y11, Y11
	VPAND      Y4, Y11, Y11
	VPXOR      Y10, Y11, Y11
	VPOR       Y11, Y8, Y8
	VMOVDQA    Y9, Y7
	ADDQ       $0x20, DX
	CMPQ       DX, CX
	JB         utf8loop
	VPTEST     Y8, Y8
	SETEQ      AL
	MOVB       AL, ret+24(FP)
	VZEROUPPER
	RET

DATA utf8t1h<>+0(SB)/1, $0x02
DATA utf8t1h<>+1(SB)/1, $0x02
DATA utf8t1h<>+2(SB)/1, $0x02
DATA utf8t1h<>+3(SB)/1, $0x02
DATA utf8t1h<>+4(SB)/1, $0x02
DATA utf8t1h<>+5(SB)/1, $0x02
DATA utf8t1h<>+6(SB)/1, $0x02
DATA utf8t1h<>+7(SB)/1, $0x02
DATA utf8t1h<>+8(SB)/1, $0x80
DATA utf8t1h<>+9(SB)/1, $0x80
DATA utf8t1h<>+10(SB)/1, $0x80
DATA utf8t1h<>+11(SB)/1, $0x80
DATA utf8t1h<>+12(SB)/1, $0x21
DATA utf8t1h<>+13(SB)/1, $0x01
DATA utf8t1h<>+14(SB)/1, $0x15
DATA utf8t1h<>+15(SB)/1, $0x49
GLOBL utf8t1h<>(SB), RODATA|NOPTR, $16

DATA utf8t1l<>+0(SB)/1, $0xe7
DATA utf8t1l<>+1(SB)/1, $0xa3
DATA utf8t1l<>+2(SB)/1, $0x83
DATA utf8t1l<>+3(SB)/1, $0x83
DATA utf8t1l<>+4(SB)/1, $0x8b
DATA utf8t1l<>+5(SB)/1, $0xcb
DATA utf8t1l<>+6(SB)/1, $0xcb
DATA utf8t1l<>+7(SB)/1, $0xcb
DATA utf8t1l<>+8(SB)/1, $0xcb
DATA utf8t1l<>+9(SB)/1, $0xcb
DATA utf8t1l<>+10(SB)/1, $0xcb
DATA utf8t1l<>+11(SB)/1, $0xcb
DATA utf8t1l<>+12(SB)/1, $0xcb
DATA utf8t1l<>+13(SB)/1, $0xdb
DATA utf8t1l<>+14(SB)/1, $0xcb
DATA utf8t1l<>+15(SB)/1, $0xcb
GLOBL utf8t1l<>(SB), RODATA|NOPTR, $16

DATA utf8t2h<>+0(SB)/1, $0x01
DATA utf8t2h<>+1(SB)/1, $0x01
DATA utf8t2h<>+2(SB)/1, $0x01
DATA utf8t2h<>+3(SB)/1, $0x01
DATA utf8t2h<>+4(SB)/1, $0x01
DATA utf8t2h<>+5(SB)/1, $0x01
DATA utf8t2h<>+6(SB)/1, $0x01
DATA utf8t2h<>+7(SB)/1, $0x01
DATA utf8t2h<>+8(SB)/1, $0xe6
DATA utf8t2h<>+9(SB)/1, $0xae
DATA utf8t2h<>+10(SB)/1, $0xba
DATA utf8t2h<>+11(SB)/1, $0xba
DATA utf8t2h<>+12(SB)/1, $0x01
DATA utf8t2h<>+13(SB)/1, $0x01
DATA utf8t2h<>+14(SB)/1, $0x01
DATA utf8t2h<>+15(SB)/1, $0x01
GLOBL utf8t2h<>(SB), RODATA|NOPTR, $16

DATA utf8n<>+0(SB)/1, $0x0f
GLOBL utf8n<>(SB), RODATA|NOPTR, $1

DATA utf8h<>+0(SB)/1, $0x80
GLOBL utf8h<>(SB), RODATA|NOPTR, $1

DATA utf8c3<>+0(SB)/1, $0x60
GLOBL utf8c3<>(SB), RODATA|NOPTR, $1

DATA utf8c4<>+0(SB)/1, $0x70
GLOBL utf8c4<>(SB), RODATA|NOPTR, $1
